kind: pipeline
name: default

steps:
- name: helloWorld
  image: dockerfile/nginx
  script
  - echo Hello World!
  
- name: debuginfo
  image: composer
  commands:
  - php -i
  - ls
  - ls ../
  
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7
  commands:
  - vendor/bin/phpunit
